#!/bin/sh

[ -x /usr/bin/logger ] || exit 1
[ -x /usr/bin/nslookup ] || exit 2

. /lib/functions.sh
. /lib/dtun/dtun.sh

config_load $DTUN_CONF

config_get enabled $INTERFACE enabled 0

[ "$enabled" == "1" ] || exit 0

[ "$ACTION" == "ifup" -o "$ACTION" == "ifdown" ] || exit 1

[ -n "$INTERFACE" ] || exit 2

if [ "$ACTION" == "ifup" ]; then
        [ -n "$DEVICE" ] || exit 3
fi

dtun_logger $HOTSCR notice "$ACTION interface $INTERFACE (${DEVICE:-unknown})"

case "$ACTION" in
	ifup)
		dtun_logger $HOTSCR notice "Running $TRACKER on $INTERFACE ($DEVICE)"
		dtun_runtrack $INTERFACE
	;;
	ifdown)
		dtun_logger $HOTSCR notice "Stopping $TRACKER on $INTERFACE"
		dtun_stoptrack $INTERFACE 
esac

exit 0
